http://www.programiz.com/r-programming/function
http://adv-r.had.co.nz/Functionals.html#lapply
http://www.saleskalab.org/teaching/tutorials/r-tutorials/
http://www.ats.ucla.edu/stat/r/library/advanced_function_r.htm
http://www.dataschool.io/dplyr-tutorial-for-faster-data-manipulation-in-r/
http://jeromyanglim.blogspot.de/2010/05/videos-on-data-analysis-with-r.html
http://www.mathtutordvd.com/public/department136.cfm
http://www.r-users.com/register/
https://www.udemy.com/introductory-statistics-part1-descriptive-statistics/
https://onlinecourses.science.psu.edu/stat505/node/55
http://zlab.bu.edu/zlab/gene.shtml
http://medias01-web.embl.de/Mediasite/Play/5ed8ac0f2fef4e2e89d8accb87d8253d1d
http://www.ebi.ac.uk/training/online/course/embo-practical-course-analysis-high-throughput-seq/statistical-concepts-and-methodologies-dat
http://meme-suite.org/index.html
http://lectures.molgen.mpg.de/swp13/pres.pdf
http://genometools.org/
http://zlab.bu.edu/zlab/gene.shtml
http://www.slideshare.net/mikaelhuss/rnaseq-differential-expression-analysis

